batch_size = 1  # 批处理大小，设置为1意味着每次处理一个样本
modelname = "groundingdino"  # 模型名称，指定为 "groundingdino"
backbone = "swin_T_224_1k"  # 背骨网络，选择 Swin Transformer-T（224x224输入大小，1k分类）
position_embedding = "sine"  # 位置编码类型，使用正弦编码（sine）
pe_temperatureH = 20  # 高度方向位置编码的温度系数
pe_temperatureW = 20  # 宽度方向位置编码的温度系数
return_interm_indices = [1, 2, 3]  # 返回的中间层索引，指定要返回的中间层（例如，第1,2,3层）
backbone_freeze_keywords = None  # 是否冻结背骨网络的关键词（暂无冻结设置）
enc_layers = 6  # 编码器层数，设置为6层
dec_layers = 6  # 解码器层数，设置为6层
pre_norm = False  # 是否在层前进行归一化，设置为False
dim_feedforward = 2048  # 前馈神经网络的维度，2048
hidden_dim = 256  # 隐藏层维度，256
dropout = 0.0  # dropout概率，0.0表示不使用dropout
nheads = 8  # 自注意力头数，设置为8
num_queries = 900  # 查询数量，设置为900
query_dim = 4  # 查询维度，设置为4
num_patterns = 0  # 模式数，设置为0
num_feature_levels = 4  # 特征层数，设置为4
enc_n_points = 4  # 编码器每个点的邻域大小，设置为4
dec_n_points = 4  # 解码器每个点的邻域大小，设置为4
two_stage_type = "standard"  # 两阶段模型类型，选择标准（standard）类型
two_stage_bbox_embed_share = False  # 是否共享两阶段的边界框嵌入，设置为False
two_stage_class_embed_share = False  # 是否共享两阶段的类别嵌入，设置为False
transformer_activation = "relu"  # transformer激活函数，设置为ReLU
dec_pred_bbox_embed_share = True  # 是否共享解码器的预测边界框嵌入，设置为True
dn_box_noise_scale = 1.0  # 噪声缩放因子，设置为1.0
dn_label_noise_ratio = 0.5  # 标签噪声比率，设置为0.5
dn_label_coef = 1.0  # 标签噪声系数，设置为1.0
dn_bbox_coef = 1.0  # 边界框噪声系数，设置为1.0
embed_init_tgt = True  # 是否初始化目标嵌入，设置为True
dn_labelbook_size = 2000  # 标签簿大小，设置为2000
max_text_len = 256  # 最大文本长度，设置为256
text_encoder_type = "bert-base-uncased"  # 文本编码器类型，使用 BERT 基础版（无大小写区分）
use_text_enhancer = True  # 是否使用文本增强器，设置为True
use_fusion_layer = True  # 是否使用融合层，设置为True
use_checkpoint = True  # 是否使用检查点，设置为True
use_transformer_ckpt = True  # 是否使用Transformer检查点，设置为True
use_text_cross_attention = True  # 是否使用文本跨注意力，设置为True
text_dropout = 0.0  # 文本dropout概率，设置为0.0表示不使用dropout
fusion_dropout = 0.0  # 融合层dropout概率，设置为0.0表示不使用dropout
fusion_droppath = 0.1  # 融合层dropout路径，设置为0.1
sub_sentence_present = True  # 是否存在子句，设置为True
